# -*- coding: utf-8 -*-
# @Author:varcer
session_file=[
        "var/lib/php/sess_PHPSESSID",
        "var/lib/php/sess_PHPSESSID",
        "tmp/sess_PHPSESSID",
        "tmp/sessions/sess_PHPSESSID",
        r"C:\phpStudy\PHPTutorial\tmp\tmp\sess_PHPSESSID",
        r"D:\phpStudy\PHPTutorial\tmp\tmp\sess_PHPSESSID",
        r"E:\phpStudy\PHPTutorial\tmp\tmp\sess_PHPSESSID"
    ]

log_file=[
"/etc/httpd/logs/access_log",
"/var/log/httpd/access_log",
r"D:\xampp\apache\logs\access.log",
r"D:\xampp\apache\logs\error.log",
"C:\WINDOWS\system32\Logfiles",
"%SystemDrive%\inetpub\logs\LogFiles",
"/usr/local/nginx/logs",
"/var/log/apache2/access.log",
"/var/log/apache/access.log",
"/var/log/httpd/access.log",
"/var/log/apache2/access_log",
"/var/log/apache/access_log",
"/var/log/httpd/access_log",
"/apache/logs/access.log",
"/apache/logs/access_log",
"/apache2/logs/access.log",
"/apache2/logs/access_log",
"/etc/httpd/logs/access_log",
"/etc/httpd/logs/access.log",
"/var/httpd/logs/access_log",
"/var/httpd/logs/access.log",
"/var/www/logs/access_log",
"/var/www/logs/access.log",
"/usr/local/apache/logs/access_log",
"/usr/local/apache/logs/access.log",
"/usr/local/apache2/logs/access_log",
"/usr/local/apache2/logs/access.log",
"/var/log/access_log",
"/var/log/access.log",
"/logs/access.log",
"/logs/access_log",
"/opt/lampp/logs/access_log",
"/opt/lampp/logs/access.log",
"/opt/xampp/logs/access.log",
"/opt/xampp/logs/access_log",
r"C:\Program Files\Apache Group\Apache\logs\access.log",
r"C:\Program Files\Apache Group\Apache\logs\access_log",
"/var/log/auth.log",
"/var/log/secure",
"/var/log/auth.log",
"/proc/self/environ",
"file1.php"
]